import type { ElementSection, Genre, Trope } from './types'

export interface OverviewTrope {
  name: string
  description: string
  genres: Genre[]
}

export const OVERVIEW_TROPES: OverviewTrope[] = [
  { name: 'The sea returns its debts', description: 'A tidal kingdom, returning shipwrecks, an unpaid promise.', genres: ['Fantasy'] },
  { name: 'The library of unwritten lives', description: 'Possible futures, a missing volume, a choice stolen.', genres: ['Fantasy'] },
  { name: 'A harvest of stars', description: 'Celestial orchards, a failed harvest, a forbidden expedition.', genres: ['Fantasy'] },
  { name: 'The bridge remembers', description: 'A sentient bridge, rival villages, a disputed crossing.', genres: ['Fantasy'] },
  { name: 'The borrowed moon', description: 'A moonless coast, stolen tides, a reluctant thief.', genres: ['Fantasy'] },
  { name: 'An orchestra for storms', description: 'Weather musicians, a silenced conductor, a gathering tempest.', genres: ['Fantasy'] },
  { name: 'The court of forgotten saints', description: 'Abandoned shrines, returning saints, a struggle for belief.', genres: ['Fantasy'] },
  { name: 'The tailor of disguises', description: 'Enchanted clothing, a masked court, a dangerous commission.', genres: ['Fantasy'] },
  { name: 'The underground spring', description: 'A desert city, secret water, a contested discovery.', genres: ['Fantasy'] },
  { name: 'The last ordinary island', description: 'An enchanted archipelago, one untouched island, an approaching change.', genres: ['Fantasy'] },
  { name: 'The silence between colonies', description: 'A quiet communications network, isolated worlds, an unauthorized voyage.', genres: ['Science Fiction'] },
  { name: 'The trial of a spaceship', description: 'A sentient vessel, disputed orders, a hearing for personhood.', genres: ['Science Fiction'] },
  { name: 'Weather by subscription', description: 'Privatized weather, a stranded farming town, a forecast rebellion.', genres: ['Science Fiction'] },
  { name: 'A thousand borrowed faces', description: 'Replaceable appearances, an identity theft, a search for trust.', genres: ['Science Fiction'] },
  { name: 'The comet settlement', description: 'A traveling colony, a dangerous orbit, a divided evacuation.', genres: ['Science Fiction'] },
  { name: 'An ocean under glass', description: 'A sealed ocean, an unexpected signal, a contested first dive.', genres: ['Science Fiction'] },
  { name: 'The last offline village', description: 'A connected planet, a disconnected community, an unwanted upgrade.', genres: ['Science Fiction'] },
  { name: 'The memory restoration shop', description: 'Damaged memories, an anonymous customer, a carefully hidden past.', genres: ['Science Fiction'] },
  { name: 'Children of two gravities', description: 'Neighboring habitats, incompatible bodies, a shared sporting challenge.', genres: ['Science Fiction'] },
  { name: 'The second sunrise', description: 'A manufactured sun, an unexplained flicker, a repair crew divided.', genres: ['Science Fiction'] },
  { name: 'The night shift pact', description: 'An all-night diner, exhausted strangers, a mutual promise.', genres: ['Contemporary'] },
  { name: 'The disputed garden', description: 'A shared courtyard, competing plans, a reluctant partnership.', genres: ['Contemporary'] },
  { name: 'A choir without a conductor', description: 'A village choir, an unexpected vacancy, a difficult performance.', genres: ['Contemporary'] },
  { name: 'The lost luggage auction', description: 'Unclaimed suitcases, a personal discovery, a search for someone.', genres: ['Contemporary'] },
  { name: 'The apartment exchange', description: 'Two distant homes, exchanged routines, an unexpected connection.', genres: ['Contemporary'] },
  { name: 'The final delivery route', description: 'A closing postal depot, undelivered letters, one last journey.', genres: ['Contemporary'] },
  { name: 'A seat at the table', description: 'A family restaurant, a new partner, a contested tradition.', genres: ['Contemporary'] },
  { name: 'The neighborhood radio hour', description: 'A small radio station, anonymous messages, a community mystery.', genres: ['Contemporary'] },
  { name: 'The long walk back', description: 'A charity trek, estranged relatives, a difficult reconciliation.', genres: ['Contemporary'] },
  { name: 'The borrowed studio', description: 'A shared workspace, competing artists, an approaching exhibition.', genres: ['Contemporary'] },
  { name: 'The inn between worlds', description: 'A crossroads inn, stranded travelers, a door that vanishes.', genres: ['Fantasy'] },
  { name: 'A crown won by cooking', description: 'A culinary kingdom, a royal contest, a stolen recipe.', genres: ['Fantasy'] },
  { name: 'Letters to the dead', description: 'Ancestral messengers, an unanswered letter, a journey below.', genres: ['Fantasy'] },
  { name: 'The dragon census', description: 'Hidden dragons, an official survey, a friendship under scrutiny.', genres: ['Fantasy'] },
  { name: 'Winter owes a debt', description: 'An endless winter, a broken bargain, a reluctant negotiator.', genres: ['Fantasy'] },
  { name: 'The smallest quest', description: 'A village bakery, a missing charm, an unexpectedly long errand.', genres: ['Fantasy'] },
  { name: 'A school for failed prophecies', description: 'Discarded chosen ones, unfinished destinies, a shared escape.', genres: ['Fantasy'] },
  { name: 'Wedding at the border', description: 'Feuding courts, an arranged wedding, an inconvenient romance.', genres: ['Fantasy'] },
  { name: 'Love across light-years', description: 'Distant stations, delayed letters, a relationship out of sync.', genres: ['Science Fiction'] },
  { name: 'The museum of Earth', description: 'A wandering museum, a disputed artifact, a search for home.', genres: ['Science Fiction'] },
  { name: 'A robot learns retirement', description: 'An automated city, an obsolete worker, an unexpected vocation.', genres: ['Science Fiction'] },
  { name: 'Election aboard the ark', description: 'A generation ship, its first election, a contested destination.', genres: ['Science Fiction'] },
  { name: 'The duplicate next door', description: 'Commercial cloning, mistaken identities, a shared disappearance.', genres: ['Science Fiction'] },
  { name: 'Garden on a dead moon', description: 'A barren moon, an impossible seed, a disputed harvest.', genres: ['Science Fiction'] },
  { name: 'Tourists at the end of time', description: 'Time-travel holidays, stranded guests, a closing departure window.', genres: ['Science Fiction'] },
  { name: 'The quiet invasion', description: 'Alien microbes, changing crops, a community divided over adaptation.', genres: ['Science Fiction'] },
  { name: 'The accidental book club', description: 'An apartment building, misdelivered books, unexpected friendships.', genres: ['Contemporary'] },
  { name: 'Two shops, one street', description: 'Neighboring businesses, a local rivalry, a reluctant romance.', genres: ['Contemporary'] },
  { name: 'The understudy summer', description: 'A community theater, an absent star, an untested ensemble.', genres: ['Contemporary'] },
  { name: 'Last stop before home', description: 'An overnight bus, stranded strangers, a shared detour.', genres: ['Contemporary'] },
  { name: 'A recipe for remembering', description: 'A family kitchen, fading memories, an unfinished cookbook.', genres: ['Contemporary'] },
  { name: 'The scholarship season', description: 'A competitive school, one scholarship, a friendship under pressure.', genres: ['Contemporary'] },
  { name: 'The unplanned reunion', description: 'A canceled flight, estranged friends, a night of unfinished conversations.', genres: ['Contemporary'] },
  { name: 'A season on the bench', description: 'A youth team, an injured captain, a different kind of leadership.', genres: ['Contemporary'] },
  { name: 'A kingdom without magic', description: 'Fading magic, rival kingdoms, a dangerous restoration.', genres: ['Fantasy'] },
  { name: 'Gods among neighbors', description: 'Everyday gods, a missing deity, a mortal investigation.', genres: ['Fantasy'] },
  { name: 'The wandering city', description: 'A migrating city, a broken route, an unlikely guide.', genres: ['Fantasy'] },
  { name: 'An empire of borrowed dreams', description: 'Traded dreams, stolen memories, a rebellion awakening.', genres: ['Fantasy'] },
  { name: 'Beyond the sealed forest', description: 'An isolated village, an ancient boundary, a forbidden rescue.', genres: ['Fantasy'] },
  { name: 'The monsters keep the peace', description: 'A fragile monster treaty, a murder, competing loyalties.', genres: ['Fantasy'] },
  { name: 'The last repair crew', description: 'A failing colony, scarce supplies, a desperate repair mission.', genres: ['Science Fiction'] },
  { name: 'Citizens of a simulation', description: 'An artificial world, missing citizens, a search outside.', genres: ['Science Fiction'] },
  { name: 'First contact, second chances', description: 'A divided Earth, alien visitors, an uneasy partnership.', genres: ['Science Fiction'] },
  { name: 'Inheritance of the stars', description: 'Abandoned starships, rival salvagers, a disputed discovery.', genres: ['Science Fiction'] },
  { name: 'A city that predicts crime', description: 'Predictive surveillance, a false accusation, a race for proof.', genres: ['Science Fiction'] },
  { name: 'Messages from tomorrow', description: 'A remote observatory, future warnings, conflicting timelines.', genres: ['Science Fiction'] },
  { name: 'The town that stayed quiet', description: 'A close-knit town, a buried scandal, an unwelcome return.', genres: ['Contemporary'] },
  { name: 'One summer to save it', description: 'A struggling neighborhood, a threatened gathering place, unlikely allies.', genres: ['Contemporary'] },
  { name: 'The family archive', description: 'An inherited house, contradictory letters, a family reckoning.', genres: ['Contemporary'] },
  { name: 'Rivals on the same team', description: 'A local competition, feuding teammates, a shared second chance.', genres: ['Contemporary'] },
  { name: 'After the evacuation', description: 'A damaged hometown, returning neighbors, a contested rebuilding.', genres: ['Contemporary'] },
  { name: 'A borrowed identity', description: 'An unfamiliar city, an assumed identity, a growing attachment.', genres: ['Contemporary'] },
]

export const TROPE_LIBRARY: Trope[] = [
  { section: 'world', name: 'Inherited weather', description: 'Families inherit responsibility for local weather along with land and debts.', genres: ['Fantasy'] },
  { section: 'world', name: 'Spirit tenancy', description: 'People share buildings with spirits whose needs shape everyday architecture.', genres: ['Fantasy'] },
  { section: 'world', name: 'Edible currency', description: 'A perishable food serves as money, making hoarding costly and timing valuable.', genres: ['Fantasy'] },
  { section: 'world', name: 'Oathbound craftsmanship', description: 'An object works only while its maker keeps a particular promise.', genres: ['Fantasy'] },
  { section: 'world', name: 'Dream pilgrimage', description: 'Travelers reach a sacred place through shared sleep rather than roads.', genres: ['Fantasy'] },
  { section: 'world', name: 'Gravity neighborhoods', description: 'Districts maintain different gravity levels, shaping accessibility and daily movement.', genres: ['Science Fiction'] },
  { section: 'world', name: 'Licensed reproduction', description: 'A settlement regulates new births around capacity, creating competing ideas of fairness.', genres: ['Science Fiction'] },
  { section: 'world', name: 'Algorithmic inheritance', description: 'Families inherit digital assistants that preserve old advice, biases, and loyalties.', genres: ['Science Fiction'] },
  { section: 'world', name: 'Disposable architecture', description: 'Buildings are routinely dismantled and rebuilt, leaving residents to preserve continuity.', genres: ['Science Fiction'] },
  { section: 'world', name: 'Nonhuman working hours', description: 'Different species organize a shared city around incompatible sleep cycles.', genres: ['Science Fiction'] },
  { section: 'world', name: 'Floodplain routines', description: 'Residents adapt ordinary life to recurring floods while disagreeing about relocation.', genres: ['Contemporary'] },
  { section: 'world', name: 'Volunteer infrastructure', description: 'Essential local services depend on unpaid work that too few people can sustain.', genres: ['Contemporary'] },
  { section: 'world', name: 'Remittance ties', description: 'Money sent home connects distant households and creates obligations across borders.', genres: ['Contemporary'] },
  { section: 'world', name: 'Protected landmark', description: 'Preservation rules safeguard a beloved place while complicating its continued use.', genres: ['Contemporary'] },
  { section: 'world', name: 'Nighttime economy', description: 'A district comes alive after dark, supporting workers largely unseen by daytime residents.', genres: ['Contemporary'] },
  { section: 'world', name: 'Rotating authority', description: 'Leadership changes on a fixed schedule, limiting power and interrupting long-term plans.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'world', name: 'Public apology ritual', description: 'Communities have a formal process for acknowledging harm, but disagree about sincere repair.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'world', name: 'Restricted maps', description: 'Accurate knowledge of routes is controlled, traded, or deliberately kept incomplete.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'world', name: 'Hospitality obligation', description: 'Hosting a visitor grants protections that can place the household in a difficult position.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'world', name: 'Conflicting calendars', description: 'Communities count time differently, complicating shared holidays, contracts, and history.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'characters', name: 'Meticulous improviser', description: 'A careful planner becomes inventive when conditions make their preparations useless.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'characters', name: 'Beloved gatekeeper', description: 'A welcoming community figure quietly decides who never gets an invitation.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'characters', name: 'Honest opportunist', description: 'Someone openly pursues personal gain but refuses to deceive the people they bargain with.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'characters', name: 'Unfinished prodigy', description: 'Early praise left a talented person unprepared for slow progress and ordinary setbacks.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'characters', name: 'Invisible organizer', description: 'A person who coordinates everything wants recognition but fears what visibility will bring.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'characters', name: 'Gentle absolutist', description: 'A kind person holds one rigid principle that makes compromise unusually difficult.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'characters', name: 'Indispensable pessimist', description: 'A habitual skeptic spots real risks but must learn when to support an uncertain attempt.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'characters', name: 'Impatient peacemaker', description: 'Someone wants reconciliation quickly and overlooks the time others need to rebuild trust.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'characters', name: 'Secret beginner', description: 'An admired expert quietly studies a skill they find unexpectedly difficult.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'characters', name: 'Affectionate competitor', description: 'Someone expresses care through competition and struggles when the other person wants cooperation.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'characters', name: 'Unwilling immortal', description: 'A long-lived person wants commitments that outlast the short lives of their companions.', genres: ['Fantasy'] },
  { section: 'characters', name: 'Spirit mediator', description: 'A negotiator understands supernatural disputes better than their own family disagreements.', genres: ['Fantasy'] },
  { section: 'characters', name: 'Hereditary villain', description: 'Someone inherits a feared family reputation and must decide which traditions deserve defending.', genres: ['Fantasy'] },
  { section: 'characters', name: 'Embodied newcomer', description: 'A formerly disembodied intelligence discovers how physical needs reshape its priorities.', genres: ['Science Fiction'] },
  { section: 'characters', name: 'Obsolete specialist', description: 'A worker retains knowledge a new system dismissed until an unusual failure makes it useful.', genres: ['Science Fiction'] },
  { section: 'characters', name: 'Relativistic parent', description: 'A traveler returns younger than the child they left behind.', genres: ['Science Fiction'] },
  { section: 'characters', name: 'Union newcomer', description: 'A new organizer must earn the trust of coworkers with more at stake than enthusiasm.', genres: ['Contemporary'] },
  { section: 'characters', name: 'Reluctant host', description: 'Someone opens their home out of obligation and discovers boundaries they never learned to set.', genres: ['Contemporary'] },
  { section: 'characters', name: 'Amateur archivist', description: 'A collector preserves overlooked lives while avoiding questions about their own past.', genres: ['Contemporary'] },
  { section: 'characters', name: 'Former hometown star', description: 'A once-celebrated achiever returns without the success everyone expected.', genres: ['Contemporary'] },
  { section: 'plot', name: 'The missing rehearsal', description: 'Skipping an apparently routine preparation leaves a relationship or plan untested.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'plot', name: 'Two legitimate claims', description: 'A discovery belongs to different people under two equally credible sets of rules.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'plot', name: 'The witness changes sides', description: 'Someone publicly withdraws support after learning how their testimony will be used.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'plot', name: 'An unwanted reward', description: 'Recognition brings a responsibility the protagonist never agreed to accept.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'plot', name: 'The replacement arrives', description: 'A substitute performs the task well but changes relationships around it.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'plot', name: 'The route closes', description: 'A familiar path becomes unavailable, forcing contact with people previously avoided.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'plot', name: 'A private kindness exposed', description: 'Public attention turns a quiet favor into a contested statement of loyalty.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'plot', name: 'The apology rejected', description: 'An attempt at repair fails because it answers a different hurt than the one caused.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'plot', name: 'Success without recognition', description: 'The important work succeeds, but credit goes elsewhere and demands a response.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'plot', name: 'The object returned', description: 'Returning something valuable reveals why its owner gave it away.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'plot', name: 'The vote splits evenly', description: 'A deadlock forces people to question who was excluded from the decision.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'plot', name: 'An ordinary day interrupted', description: 'A small disruption reveals how much unseen work sustains a normal routine.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'plot', name: 'The bargain expires', description: 'Temporary protections end before the characters have found a lasting solution.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'plot', name: 'A lesson misapplied', description: 'A once-useful rule causes harm when used in a situation it was never meant for.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'plot', name: 'The familiar chooses', description: 'A magical companion pursues its own need at a moment its partner expects obedience.', genres: ['Fantasy'] },
  { section: 'plot', name: 'The curse protects something', description: 'Breaking a harmful enchantment would also remove the boundary containing a greater danger.', genres: ['Fantasy'] },
  { section: 'plot', name: 'The backup disagrees', description: 'A restored version rejects decisions made by the person whose place it is taking.', genres: ['Science Fiction'] },
  { section: 'plot', name: 'The translation improves', description: 'A better translation reveals that an accepted agreement never meant the same thing to both sides.', genres: ['Science Fiction'] },
  { section: 'plot', name: 'The inspection date', description: 'An approaching inspection exposes the gap between how an institution looks and how it works.', genres: ['Contemporary'] },
  { section: 'plot', name: 'The group chat leaks', description: 'Private remarks circulate beyond their intended audience and force overdue conversations.', genres: ['Contemporary'] },
  { section: 'world', name: 'Magic as a commons', description: 'A community shares a finite source of magic and must agree how to replenish it.', genres: ['Fantasy'] },
  { section: 'world', name: 'Names with consequences', description: 'Names grant rights or powers, making renaming a consequential public act.', genres: ['Fantasy'] },
  { section: 'world', name: 'Domestic enchantments', description: 'Small household spells require maintenance, creating trades, routines, and petty disputes.', genres: ['Fantasy'] },
  { section: 'world', name: 'Courts of the dead', description: 'Ancestors retain a formal voice in laws that the living must obey.', genres: ['Fantasy'] },
  { section: 'world', name: 'Repair culture', description: 'Tools and machines pass through generations because replacement parts are rare.', genres: ['Science Fiction'] },
  { section: 'world', name: 'Programmable bodies', description: 'Physical modification is ordinary, but access and social expectations vary.', genres: ['Science Fiction'] },
  { section: 'world', name: 'Orbital seasons', description: 'Travel and trade follow narrow windows set by moving planets and stations.', genres: ['Science Fiction'] },
  { section: 'world', name: 'Shared machine governance', description: 'Residents negotiate civic decisions with a system that follows outdated priorities.', genres: ['Science Fiction'] },
  { section: 'world', name: 'Third place', description: 'A library, cafe, or recreation center connects people who otherwise never meet.', genres: ['Contemporary'] },
  { section: 'world', name: 'Seasonal town', description: 'An influx of visitors transforms local work, friendships, and access to housing.', genres: ['Contemporary'] },
  { section: 'world', name: 'Informal care network', description: 'Neighbors exchange childcare, meals, and favors outside official institutions.', genres: ['Contemporary'] },
  { section: 'world', name: 'School district boundary', description: 'A line on a map divides opportunity and shapes family decisions.', genres: ['Contemporary'] },
  { section: 'world', name: 'Gift economy', description: 'Giving creates obligations whose meaning differs between communities.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'world', name: 'Festival truce', description: 'A recurring celebration temporarily suspends rivalries under carefully observed rules.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'world', name: 'Two working languages', description: 'Official business and everyday life use different languages, shifting who gets heard.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'world', name: 'The long road', description: 'A difficult route shapes trade, migration, and how far news can travel.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'characters', name: 'Ambitious best friend', description: 'A supportive friend wants the same scarce opportunity and cannot keep pretending otherwise.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'characters', name: 'Earnest troublemaker', description: 'Someone acts from generous intentions while repeatedly overlooking practical consequences.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'characters', name: 'Retired expert', description: 'A specialist wants an ordinary life but finds their skills still needed.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'characters', name: 'Patient investigator', description: 'A quiet observer makes progress by listening to people others dismiss.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'characters', name: 'Charming avoider', description: 'An engaging companion uses humor to postpone a difficult obligation.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'characters', name: 'Keeper of small promises', description: 'Someone with little authority earns trust by reliably doing ordinary things.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'characters', name: 'Late beginner', description: 'A newcomer risks embarrassment to pursue a calling others consider too late.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'characters', name: 'Homesick adventurer', description: 'A traveler longs for discovery and the comfort they left behind.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'characters', name: 'Successful younger sibling', description: 'An accomplished sibling resents being treated as someone who still needs protection.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'characters', name: 'Forgiven but unchanged', description: 'Someone accepts a second chance without yet understanding what must change.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'characters', name: 'Practical spellkeeper', description: 'A magical specialist treats wonders as maintenance work and knows where the shortcuts fail.', genres: ['Fantasy'] },
  { section: 'characters', name: 'Prophecy skeptic', description: 'Someone charged with interpreting destiny distrusts the predictions they must announce.', genres: ['Fantasy'] },
  { section: 'characters', name: 'Copy with different memories', description: 'A duplicate shares an origin but has developed loyalties the original cannot accept.', genres: ['Science Fiction'] },
  { section: 'characters', name: 'Planetbound navigator', description: 'A gifted route planner has never traveled beyond their home settlement.', genres: ['Science Fiction'] },
  { section: 'characters', name: 'New guardian', description: 'An unexpected caregiver must learn responsibility while grieving their former plans.', genres: ['Contemporary'] },
  { section: 'characters', name: 'Local celebrity', description: 'A familiar public figure struggles to separate community expectations from private needs.', genres: ['Contemporary'] },
  { section: 'plot', name: 'The swapped invitation', description: 'A misdirected invitation puts someone in a setting where their presence changes the stakes.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'plot', name: 'A favor passed along', description: 'A small act of help travels through several people before returning at a crucial moment.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'plot', name: 'Practice becomes the test', description: 'An apparently low-stakes rehearsal exposes the weakness that will matter later.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'plot', name: 'The wrong suspect', description: 'Evidence against an easy target distracts from a less comfortable explanation.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'plot', name: 'An honest misunderstanding', description: 'People act on different incomplete truths until a conversation changes their choices.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'plot', name: 'The invitation declined', description: 'Refusing an opportunity reveals a need more important than the expected reward.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'plot', name: 'A shared task', description: 'An ordinary job forces estranged people to spend time together without resolving everything at once.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'plot', name: 'The plan succeeds too well', description: 'Getting exactly what was requested exposes the flaw in the original wish.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'plot', name: 'Passing the responsibility', description: 'A protagonist must trust someone else with the decisive task.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'plot', name: 'The small celebration', description: 'A moment of shared joy reveals what the characters stand to lose.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'plot', name: 'Evidence in plain sight', description: 'A familiar object gains new meaning after a key assumption changes.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'plot', name: 'The imperfect goodbye', description: 'A departure arrives before every conflict can be resolved.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'plot', name: 'A spell obeys literally', description: 'An enchantment fulfills its exact wording and forces a more thoughtful request.', genres: ['Fantasy'] },
  { section: 'plot', name: 'Arrival before the warning', description: 'A traveler reaches a destination before the message meant to prepare it.', genres: ['Science Fiction'] },
  { section: 'plot', name: 'The canceled event', description: 'A long-planned occasion falls through, forcing people to confront why it mattered.', genres: ['Contemporary'] },
  { section: 'plot', name: 'Choosing a smaller victory', description: 'A character gives up a grand outcome to secure something specific and lasting.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'world', name: 'Seasonal magic', description: 'Power changes with the seasons, reshaping work, travel, and conflict.', genres: ['Fantasy'] },
  { section: 'world', name: 'Living geography', description: 'Forests, rivers, or mountains move and bargain with their inhabitants.', genres: ['Fantasy'] },
  { section: 'world', name: 'Competing faiths', description: 'Religious traditions disagree about a shared miracle and who may interpret it.', genres: ['Fantasy', 'Contemporary'] },
  { section: 'world', name: 'Border market', description: 'A trading place brings hostile communities together under fragile rules.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'world', name: 'Artificial ecosystem', description: 'Daily life depends on a maintained environment with no easy replacement.', genres: ['Science Fiction'] },
  { section: 'world', name: 'Delayed communication', description: 'Distant settlements must make decisions before messages can reach home.', genres: ['Science Fiction'] },
  { section: 'world', name: 'Memory economy', description: 'Memories can be bought and sold, changing identity, evidence, and inequality.', genres: ['Science Fiction', 'Fantasy'] },
  { section: 'world', name: 'Company town', description: 'One employer controls housing, opportunity, and the cost of dissent.', genres: ['Contemporary', 'Science Fiction'] },
  { section: 'world', name: 'Changing neighborhood', description: 'New arrivals and longtime residents contest what their shared home should become.', genres: ['Contemporary'] },
  { section: 'world', name: 'Ritual of belonging', description: 'A local tradition decides who is welcomed, trusted, or kept outside.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'world', name: 'Disputed history', description: 'Public monuments tell a story that private records contradict.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'world', name: 'Unsafe sanctuary', description: 'A place of refuge offers protection under a rule that may become unbearable.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'characters', name: 'Loyal dissenter', description: 'A devoted insider challenges the institution they still hope to save.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'characters', name: 'Compromised mentor', description: 'A trusted teacher has useful wisdom and an unresolved wrong to answer for.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'characters', name: 'Protective rival', description: 'A competitor obstructs the protagonist while quietly shielding them from danger.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'characters', name: 'Outsider translator', description: 'Someone bridges two communities but belongs fully to neither.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'characters', name: 'Principled opponent', description: 'An antagonist pursues a defensible goal through unacceptable methods.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'characters', name: 'Unreliable witness', description: 'A sincere witness remembers events incorrectly and has reasons to resist correction.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'characters', name: 'Exhausted caretaker', description: 'Someone who holds everyone together must finally ask for help.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'characters', name: 'Apprentice without a gift', description: 'An aspiring practitioner must find a place in a culture built around innate magic.', genres: ['Fantasy'] },
  { section: 'characters', name: 'Artificial heir', description: 'A created person inherits obligations their maker never explained.', genres: ['Science Fiction'] },
  { section: 'characters', name: 'Returning sibling', description: 'A family member comes home changed and disrupts the roles everyone remembers.', genres: ['Contemporary'] },
  { section: 'characters', name: 'Former true believer', description: 'A disillusioned follower knows the cause intimately but distrusts their own judgment.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'characters', name: 'Accidental leader', description: 'A practical helper becomes responsible for people with incompatible needs.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'plot', name: 'Uneasy alliance', description: 'Opponents cooperate on a shared threat while negotiating what comes afterward.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'plot', name: 'False victory', description: 'An apparent success exposes the larger problem it helped conceal.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'plot', name: 'The missing account', description: 'An absent witness or record changes the meaning of an accepted story.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'plot', name: 'A deadline moves closer', description: 'New information cuts the time available and forces a costly shortcut.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'plot', name: 'The rescue refused', description: 'The person being rescued rejects the plan and reveals an overlooked stake.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'plot', name: 'Truth at a cost', description: 'Revealing the truth would also hurt someone the protagonist promised to protect.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'plot', name: 'A promise comes due', description: 'An earlier commitment becomes inconvenient precisely when it matters most.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'plot', name: 'Return with new eyes', description: 'Revisiting a familiar place reveals what the protagonist previously misunderstood.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'plot', name: 'Broken enchantment', description: 'Undoing a spell restores one thing while taking away something people depend on.', genres: ['Fantasy'] },
  { section: 'plot', name: 'Signal from the lost', description: 'A transmission from a vanished mission forces a choice between pursuit and safety.', genres: ['Science Fiction'] },
  { section: 'plot', name: 'The public hearing', description: 'A private conflict becomes public, giving overlooked people a chance to intervene.', genres: ['Contemporary'] },
  { section: 'plot', name: 'Repair instead of revenge', description: 'A final opportunity to retaliate competes with the harder work of rebuilding.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'world', name: 'Hidden cost', description: 'Power, progress, or comfort always asks for something in return.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'world', name: 'Decaying golden age', description: 'The world still depends on the remains of a better era.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'world', name: 'Unequal access', description: 'A resource or institution divides people by who can reach it.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'world', name: 'Dystopian government', description: 'A ruling system makes ordinary life orderly, controlled, and morally costly.', genres: ['Science Fiction', 'Contemporary'], followUps: [{ section: 'characters', name: 'Female savior', description: 'A central woman is positioned as the exceptional person who can rescue everyone, creating pressure around agency and expectation.', fields: { motivation: '', goal: '', weakness: '', background: '' } }] },
  { section: 'characters', name: 'Reluctant heir', description: 'Someone inherits a role they never wanted and cannot safely refuse.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'characters', name: 'Rivals with respect', description: 'Opponents recognize each other’s ability even while they clash.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'characters', name: 'False confidence', description: 'A capable person hides the fear that drives their worst choices.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'plot', name: 'The revealed bargain', description: 'A past agreement explains the present crisis and changes its stakes.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'plot', name: 'Point of no return', description: 'A choice closes the path back to the old life.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
  { section: 'plot', name: 'Escalating consequence', description: 'Each attempted solution creates a more difficult problem.', genres: ['Fantasy', 'Science Fiction', 'Contemporary'] },
]

export function tropesFor(section: ElementSection, genre: Genre): Trope[] {
  return TROPE_LIBRARY.filter((trope) => trope.section === section && trope.genres.includes(genre))
}
